=== ragsthename/GITR/HPDriverPackManifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SoftPaqTitle" type="xs:string"/>
	<xs:element name="Version" type="xs:string"/>
	<xs:element name="SoftPaqNumber" type="xs:string"/>
	<xs:element name="Dir" type="xs:string"/>
	<xs:element name="IncludedDir">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The list of locations to driver files in a SoftPaq</xs:documentation>
			</xs:annotation>
			<xs:sequence>
				<xs:element ref="Dir" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SoftPaq">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SoftPaqNumber"/>
				<xs:element ref="SoftPaqTitle"/>
				<xs:element ref="Version"/>
				<xs:element ref="IncludedDir"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DriverPackTitle" type="xs:string"/>
	<xs:element name="CreatedTime" type="xs:dateTime"/>
	<xs:element name="Author" type="xs:string"/>
	<xs:element name="Tool" type="xs:string"/>
	<xs:element name="GeneratedBy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tool"/>
				<xs:element ref="Version"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Info">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The general information about an HP driver pack</xs:documentation>
			</xs:annotation>
			<xs:sequence>
				<xs:element ref="DriverPackTitle"/>
				<xs:element ref="CreatedTime"/>
				<xs:element ref="Author"/>
				<xs:element ref="GeneratedBy"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IncludedSoftPaq">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SoftPaq" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="HPDriverPack">
		<xs:annotation>
			<xs:documentation>All the information about an HP driver pack</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Info"/>
				<xs:element ref="IncludedSoftPaq"/>
			</xs:sequence>
			<xs:attribute name="schemaVersion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="\d{1,5}\.\d{1,5}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ragsthename/GITR/HPDriverPackManifest.xml
<?xml version="1.0" encoding="utf-8"?>
<HPDriverPack schemaVersion="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HPDriverPackManifest.xsd">
  <Info>
    <DriverPackTitle>Z640</DriverPackTitle>
    <CreatedTime>2015-08-24T16:52:22</CreatedTime>
    <Author>HP</Author>
    <GeneratedBy>
      <Tool>HP Driver Pack Builder Engine</Tool>
      <Version>1.1.2.0</Version>
    </GeneratedBy>
  </Info>
  <IncludedSoftPaq>
    <SoftPaq>
      <SoftPaqNumber>sp72211</SoftPaqNumber>
      <SoftPaqTitle>Intel Rapid Storage Technology Enterprise</SoftPaqTitle>
      <Version>4.3.0.1198</Version>
      <IncludedDir>
        <Dir>C:\HPSDM\bld\Z640\wt64\storage\intel\sp72211\64bit_RSTe_4.3.0.1198_F6_Drivers\RSTe_f6_iaStorA_win8_win10_64</Dir>
      </IncludedDir>
    </SoftPaq>
    <SoftPaq>
      <SoftPaqNumber>sp72180</SoftPaqNumber>
      <SoftPaqTitle>Intel Chipset Drivers for Microsoft Windows</SoftPaqTitle>
      <Version>10.1.2.8</Version>
      <IncludedDir>
        <Dir>C:\HPSDM\bld\Z640\wt64\chipset\intel\sp72180\Drivers</Dir>
      </IncludedDir>
    </SoftPaq>
    <SoftPaq>
      <SoftPaqNumber>sp72024</SoftPaqNumber>
      <SoftPaqTitle>Intel Network Connections Drivers Release 20.2</SoftPaqTitle>
      <Version>R20.2_377786</Version>
      <IncludedDir>
        <Dir>C:\HPSDM\bld\Z640\wt64\network\intel\sp72024\DMIX+DRIVERS\WIN10-x64\DRIVERS\Legacy</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\network\intel\sp72024\DRIVERS\E1C\WIN10-x64</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\network\intel\sp72024\DRIVERS\E1D\WIN10-x64</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\network\intel\sp72024\DRIVERS\E1R\WIN10-x64</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\network\intel\sp72024\DRIVERS\IXN\WIN10-x64</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\network\intel\sp72024\DRIVERS\IXT\WIN10-x64</Dir>
      </IncludedDir>
    </SoftPaq>
    <SoftPaq>
      <SoftPaqNumber>sp71837</SoftPaqNumber>
      <SoftPaqTitle>AMD FirePro Unified Graphics Driver Windows 10 (64-Bit)</SoftPaqTitle>
      <Version>15.20.1045</Version>
      <IncludedDir>
        <Dir>C:\HPSDM\bld\Z640\wt64\graphics\amd\sp71837\Packages\Drivers\Display\WT6A_INF</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\graphics\amd\sp71837\Packages\Drivers\WDM\HDMI\WT64A</Dir>
      </IncludedDir>
    </SoftPaq>
    <SoftPaq>
      <SoftPaqNumber>sp71836</SoftPaqNumber>
      <SoftPaqTitle>NVIDIA Quadro Professional Driver Windows 10 (x64)</SoftPaqTitle>
      <Version>353.30</Version>
      <IncludedDir>
        <Dir>C:\HPSDM\bld\Z640\wt64\graphics\nvidia\sp71836\Display.Driver</Dir>
        <Dir>C:\HPSDM\bld\Z640\wt64\graphics\nvidia\sp71836\HDAudio</Dir>
      </IncludedDir>
    </SoftPaq>
    <SoftPaq>
      <SoftPaqNumber>sp71832</SoftPaqNumber>
      <SoftPaqTitle>Realtek Audio Driver Windows 7/8/8.1/10</SoftPaqTitle>
      <Version>6.0.1.7548</Version>
      <IncludedDir>
        <Dir>C:\HPSDM\bld\Z640\wt64\audio\realtek\sp71832\Vista64</Dir>
      </IncludedDir>
    </SoftPaq>
  </IncludedSoftPaq>
</HPDriverPack>
